# Generated by Django 5.1.1 on 2024-10-07 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('product_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
