# Generated by Django 5.1.1 on 2024-10-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_reviewproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
