# Generated by Django 5.1.1 on 2024-10-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='alternate_number',
        ),
    ]
