# Generated by Django 5.1.1 on 2024-10-08 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_remove_address_alternate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('product_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='image', upload_to='image')),
                ('order_status', models.IntegerField(default='pending')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.IntegerField(default=1),
        ),
    ]
